# Generated by Django 4.2 on 2023-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='code_executed',
            field=models.BooleanField(default=False),
        ),
    ]
