# Generated by Django 4.2 on 2023-09-13 04:50

from django.db import migrations, models
import django.db.models.deletion
import hr_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0004_employees_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('reimbursement_status', models.IntegerField(blank=True, default=0, null=True)),
                ('query', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('approved_by', models.TextField(blank=True, default='', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_bill', to='hr_management_app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('reason', models.CharField(choices=[('', 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Other', 'Other')], max_length=50, null=True)),
                ('attachment', models.FileField(null=True, upload_to=hr_management_app.models.get_upload)),
                ('sr_no', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management_app.reimbursement_bill')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management_app.employees')),
            ],
        ),
        migrations.DeleteModel(
            name='Reimbursement',
        ),
    ]
