# Generated by Django 4.2 on 2023-10-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0005_reimbursement_bill_reimbursement_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
