# Generated by Django 4.2 on 2023-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='else_executed',
            field=models.BooleanField(default=True),
        ),
    ]
