# Generated by Django 4.2 on 2023-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0007_employeeleave_else_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='else_executed',
            field=models.BooleanField(default=False),
        ),
    ]
