# Generated by Django 4.1.7 on 2024-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0008_alter_employeeleave_else_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement_data',
            name='reason',
            field=models.CharField(choices=[('', 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Sales Incentive', 'Sales Incentive'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
